- pipeline: "Pipeline"
  on: "CLICK"
  refs:
  - "refs/heads/dev"
  - ":default"
  fail_on_prepare_env_warning: true
  resources: "NANO"
  actions:
  - action: "Compress images"
    type: "IMAGE_COMPRESSION"
    disabled: true
    local_path: ".buddy/source/"
    destination: ".buddy/target/"
    level: "3"
    types: "png,gif,svg"
    ignore_errors: true
